INSERT INTO school(id, location, name) values (1,'Bauru, Guarantinguetá e Jaboticabal (SP)', 'CTI');
INSERT INTO test(id, name, year, school_id) values (17, 'cti2019', 2019, 1);

INSERT INTO school(id, location, name) values (2,'Campinas (SP)', 'Cotuca');
INSERT INTO test(id, name, year, school_id) values (54, 'cotuca2020', 2020, 2);
INSERT INTO test(id, name, year, school_id) values (36, 'cotuca2019', 2019, 2);
INSERT INTO test(id, name, year, school_id) values (37, 'cotuca2018', 2018, 2);
INSERT INTO test(id, name, year, school_id) values (38, 'cotuca2017', 2017, 2);
INSERT INTO test(id, name, year, school_id) values (39, 'cotuca2016', 2016, 2);

INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1938, 'Português','B', '', '||A:que pode ser traduzida, em português, por “evento esportivo”.#@||B:usada em algumas modalidades esportivas.#@||C:criada em bares de jazz de Chicago.#@||D:que, em português, significa “porta que bate”.#@||E:característica de meios musicais, principalmente de jazz.#@', '', 'Leia o texto a seguir para responder às questões 1, 2, 3 e 4.

A palavra slam é uma onomatopeia da língua inglesa utilizada para indicar o som de uma “batida” de porta ou janela, seja esse movimento leve ou abrupto. Algo próximo do nosso “pá!” em língua portuguesa. A onomatopeia foi emprestada por Marc Kelly Smith, um trabalhador da construção civil e poeta, para nomear o Uptown Poetry Slam, evento poético que surgiu em Chicago, em 1984. O termo slam é utilizado para se referir às finais de torneios de baseball, tênis, bridge, basquete, por exemplo. Smith nomeou também slam os campeonatos de performances poéticas que organizava e no qual os slammers (poetas) eram avaliados com notas pelo público presente, inicialmente em um bar de jazz em Chicago, depois nas periferias da cidade. A iniciativa “viralizou”, como se diz hoje, contagiando outras cidades dos Estados Unidos e, mais tarde, ganhou o mundo. Poesia é o mundo.', 'De acordo com o texto, “slam” é uma palavra', '1', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1939, 'Português','B', '', '||A:Nossa! Quanta cultura em uma só batida!#@||B:É possível fazer poesia a partir do coaxar de um sapo?#@||C:Futebol é uma palavra originada do inglês football.#@||D:Gostaria de conseguir deletar emoções que me fazem mal.#@||E:Viu o novo post que viralizou?#@', '', '', 'Pela leitura do texto, é possível compreender como funciona uma “onomatopeia”. Escolha a alternativa que melhor apresenta essa figura de linguagem na construção de uma palavra.', '2', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1940, 'Português','D', '', '||A:Ao denominar “slam” os eventos poéticos, Smith retomou a avaliação do público neles presente.#@||B:A ambientação em bares de jazz fez os slammers se tornarem campeonatos de poesia.#@||C:A  mudança dos  slams  dos  bares  de  jazz  de  Chicago  para  as  periferias  da  cidade  foi  responsável  pela “viralização” do evento nos Estados Unidos.#@||D:A avaliação do público tornava os slams populares, o que os levou a “viralizarem” pelo mundo.#@||E:A referência à batida de uma janela fez do slam uma espécie de “janela para o mundo”.#@', '', '', 'Qual dessas afirmativas melhor interpreta o texto apresentado?', '3', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1941, 'Português','A', '', '||A:“Smith”#@||B:“Slam”#@||C:“Slam” e “campeonatos de performances poéticas”#@||D:“campeonatos de performances poéticas”#@||E:“performances poéticas”#@', '', '', '“Smith nomeou também slam os campeonatos de performances poéticas que organizava e no qual os slammers (poetas) eram avaliados com notas pelo público presente, inicialmente em um bar de jazz em Chicago, depois nas periferias da cidade”. Sobre o trecho reproduzido, é possível afirmar que o sujeito do verbo “organizava” é:', '4', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1942, 'Português','E', '', '||A:a todo o povo brasileiro, que apaga da história todos os seus símbolos de resistência negra.#@||B:ao Estado brasileiro, que apaga da história todos os seus símbolos de resistência negra.#@||C:ao povo brasileiro, o qual tende a vêla como um sujeito que não possui melanina suficiente para ter sua pele retinta, o que configuraria os traços marcados de seus ancestrais.#@||D:às  políticas  de  embranquecimento  do  Estado,  que  pressupõem  a  diversidade  social,  étnica  e  cultural  do Brasil.#@||E:às políticas de embranquecimento do Estado, que tendem a negar a diversidade social, étnica e cultural do#@', '', 'O texto a seguir é um trecho de um slam transcrito a partir da performance de sua autora, Midria, em um programa de televisão da TV Cultura. Leia-o para responder às questões 5, 6 e 7

Eu tenho um problema: meu ascendente é em Áries.
E eu tenho outro problema: é que eu sou a menina que nasceu sem cor.
Pra alguns eu sou "preta", para outras eu sou Preta, para muitos e muitos eu sou parda. (...) Eu sou a menina que nasceu sem cor porque eu nasci num país sem memória, com amnésia, que apaga da história todos os seus símbolos de resistência negra, que embranquece a sua população e trajetória a cada brecha, (...) E eu tenho outro problema... pô, eu não sei dar cambalhota e não importa que pra alguns eu seja a menina que nasceu sem cor, que falte melanina pra minha pele ser retinta, que os meus traços não sejam tão marcados.
O colorismo é uma política de embranquecimento do Estado que por muito tempo fez com que eu odiasse meus traços genéticos do meu pai herdados.
Me odiasse, me mutilasse, meu cabelo alisasse.
Meninas pretas não brincam com bonecas pretas, mas faço questão de botar no meu texto que pretas e pretos estão se armando, se amando, porque me chamam por aí de parda, morena, moreninha, mestiça, mulata, café com leite, marrom bombom... Por muito tempo eu fui a menina que nasceu sem cor, até que um dia gritaram-me: NEGRA. E eu respondi.', 'De acordo com o texto, Midria, ao afirmar que é uma menina que nasceu sem cor, faz uma crítica', '5', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1943, 'Português','C', '', '||A:Folhagem#@||B:Dança#@||C:Impaciente#@||D:Desfazer#@||E:Camponês#@', '', '', 'Analise  o  processo  de  formação  da  palavra  “embranquecimento”,  avaliando  se  há  prefixos  e/ou  sufixos adicionados a um ou mais radicais. Outra palavra formada por esse mesmo processo é:', '6', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1944, 'Português','D', 'https://i.imgur.com/5sXX4Sc.png', '||A:Meu ritual de preparação para a escrita talvez seja a vida em si. Me entregar aos momentos que surgem e, se rolar, escreviver por eles, como diz a Conceição Evaristo.#@||B:Antes de escrever “A menina que nasceu sem cor”, eu  não  tinha  nada  a  perder  e, depois  que  escrevi, continuei não tendo. A viralização que essa poesia teve é uma dádiva sem fim, que eu valorizo, mas que não era a minha meta primeira.#@||C:Se  eu  escrevo,  é, antes  de  qualquer  coisa,  pra  fazer  sentido  pra  mim  mesma.  Se  não  tô  escrevendo, provavelmente é porque não tô com muita coisa pra dizer ou ainda não passei pelos processos necessários para sintetizar minhas vivências em poesia.#@||D:Minha poesia é bem personalista, quase sempre na primeira pessoa. Sou eu contando minha história, sobre ser da periferia, sobre descobrir minha negritude, sobre descobrir meu prazer, minha autonomia sobre minha estética, e o que mais fizer sentido partilhar.#@||E:Acho que, ao longo dos anos, assim como eu amadureci, minha escrita floresceu também. Meus textos se#@', '', '', 'As alternativas abaixo são trechos extraídos de uma entrevista de Midria, autora do slam “A menina que nasceu sem  cor”,  para  o  blog  “Como  eu  escrevo”. Qual  das alternativas melhor retrata a temática presente no slam “A menina que nasceu sem cor”?', '7', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1945, 'Português','D', '', '||A:Uso da palavra “você”, cuja grafia não é a formalizada pelos dicionários.#@||B:Uso da palavra “te”, que já caiu em desuso e não é recomendada em textos formais.#@||C:Ausência de vírgulas na frase, com a construção de uma frase muito longa.#@||D:Uso das palavras “te” e “você” num mesmo texto, misturando as pessoas verbais.#@||E:Uso da palavra “vê”, por estar conjugada no modo imperativo.#@', '', 'Leia o texto a seguir para responder às questões 8 e 9.', 'Essa imagem foi fotografada em um banheiro público e apresenta uma frase de autor desconhecido. Qual das alternativas a seguir melhor analisa a informalidade da linguagem da frase, característica do contexto apresentado, em relação à norma padrão?', '8', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1946, 'Português','B', 'https://i.imgur.com/hLjYo1l.png', '||A:alterar as características próprias do espaço onde ela foi registrada.#@||B:aproximar autor e leitor, para que o objetivo da frase seja atingido.#@||C:construir um deboche do leitor, que se sentiria feliz ao ler o texto.#@||D:satirizar frases de banheiro que trazem sentidos pejorativos.#@||E:apresentar uma linguagem mais atual, para atingir apenas os jovens.#@', '', '', 'A informalidade da linguagem usada na frase pode ter como objetivo:', '9', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1947, 'Português','A', '', '||A:egoístas esperam sempre ganhar algo em troca de suas ações.#@||B:egoístas nunca atendem ao que lhes é proposto.#@||C:um mundo menos egoísta é possível, desde que se apresente alguma vantagem ao povo.#@||D:um mundo menos egoísta não é possível, uma vez que ninguém se preocupa em propor alternativas não individualistas.#@||E:a maior parte das pessoas está preocupada com o bemestar coletivo e não se deixa enganar por propostas#@', '', '', 'A partir dos quadrinhos, é possível interpretar que a tirinha de André Dahmer sugere que:', '10', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1948, 'Português','D', '', '||A:O modo verbal empregado é o subjuntivo, sugerindo uma ação possível aos ouvintes.#@||B:O modo verbal empregado é o subjuntivo, apresentando uma possibilidade de ação possível aos ouvintes.#@||C:O modo verbal empregado é o subjuntivo, mostrando a incerteza do falante em relação à ação sugerida aos ouvintes.#@||D:O modo verbal empregado é o imperativo, apresentando um convite a todos os ouvintes.#@||E:O modo verbal empregado é o imperativo, apresentando um conselho a todos os ouvintes.#@', '', '', 'Qual das alternativas a seguir melhor indica o modo verbal e uma interpretação para o uso do verbo “venham” nos quadrinhos?', '11', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1949, 'Português','E', '', '||A:Defesa da arte clássica como padrão artístico brasileiro.#@||B:Defesa da liberdade de expressão dos autores brasileiros.#@||C:Defesa de uma arte que cultue e promova os símbolos nacionais do Brasil.#@||D:Defesa de uma arte que tenha compromisso apenas com temas de denúncia social.#@||E:Defesa de uma arte genuinamente popular.#@', '', 'Leia, a seguir, fragmentos do Manifesto da Antropofagia periférica, escrito pelo poeta Sérgio Vaz, para responder à questão 12.
Manifesto da Antropofagia periférica
A Periferia nos une pelo amor, pela dor e pela cor.
Dos becos e vielas há de vir a voz que grita contra o silêncio que nos pune. Eis que surge das ladeiras um povo lindo e inteligente galopando contra o passado. A favor de um futuro limpo, para todos os brasileiros.
A favor de um subúrbio que clama por arte e cultura, e universidade para a diversidade. (...)
Contra a arte patrocinada pelos que corrompem a liberdade de opção. Contra a arte fabricada para destruir o senso crítico, a emoção e a sensibilidade que nasce da múltipla escolha.
A Arte que liberta não pode vir da mão que escraviza.
A favor do batuque da cozinha que nasce na cozinha e sinhá não quer. Da poesia periférica que brota na porta do bar. [...]
Da Literatura das ruas despertando nas calçadas.
A Periferia unida, no centro de todas as coisas.
Contra o racismo, a intolerância e as injustiças sociais das quais a arte vigente não fala.
Contra o artista surdo-mudo e a letra que não fala.
É preciso sugar da arte um novo tipo de artista: o artista-cidadão. Aquele que na sua arte não revoluciona o mundo, mas também não compactua com a mediocridade que imbeciliza um povo desprovido de oportunidades. Um artista a serviço da comunidade, do país. (...) [...]
Contra a barbárie que é a falta de bibliotecas, cinemas, museus, teatros e espaços para o acesso à produção cultural. Contra reis e rainhas do castelo globalizado e quadril avantajado. [...]
Contra os covardes e eruditos de aquário.
Contra o artista serviçal escravo da vaidade.
[...] A Arte que liberta não pode vir da mão que escraviza.
Por uma Periferia que nos une pelo amor, pela dor e pela cor.
 É TUDO NOSSO!', 'Ao se publicar um Manifesto, buscase formal e publicamente a transmissão de opiniões, decisões, intenções e ideias. Nos trechos transcritos do Manifesto da Antropofagia periférica, é possível identificar o que se afirma em:', '12', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1950, 'Matemática','A', 'https://i.imgur.com/G0MMdpi.png@https://i.imgur.com/IwRhwok.png', '||A:R$ 88,10#@||B:R$ 87,10#@||C:R$ 39,10#@||D:R$ 48,10#@||E:R$ 16,00#@', '', 'Carrinho de rolimã é um dos brinquedos tradicionais de criança. A figura a seguir ilustra os procedimentos para a confecção de um carrinho. Adaptado de http://predadorpredador.blogspot.com/2012/03/carrinhoderolima.html. Acesso em 26/07/2019.', 'Considere as tabelas apresentadas e calcule o custo mínimo do material necessário para confeccionar um carrinho.', '13', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1951, 'Matemática','B', '', '||A:285#@||B:570#@||C:760#@||D:950#@||E:1330#@', '', '', 'Em uma escola, 35% dos alunos leem jornal e 55% leem revista. Sabese que 25% não leem jornal nem revista e que a escola possui 3800 alunos. Qual é o número de alunos que leem jornal e revista?', '14', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1952, 'Matemática','B', 'https://i.imgur.com/AzZFlv0.png', '||A:1,82#@||B:1,80#@||C:1,79#@||D:1,83#@||E:1,81#@', '', '', 'Um time de voleibol tem 12 jogadores: 6 titulares e 6 reservas. (Adaptado de https://jogos4.weebly.com/quantosjogadorestemovoleibol.html. Acesso em 27/07/2019).  Durante uma partida de voleibol, a estatura média dos jogadores em quadra era de 1,78 m. O técnico substituiu um jogador titular de 1,72 m por um reserva de 1,84 m. Sendo assim, a estatura média dos jogadores em quadra passou a ser, em metros, de:', '15', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1953, 'Matemática','E', '', '||A:R$ 1.100,00#@||B:R$ 535,00#@||C:R$ 1.035,00#@||D:R$ 1.125,00#@||E:R$ 1.070,00#@', '', '', 'Uma quantia em dinheiro foi dividida entre Alberto, Bruno e Carlos, de forma que as partes recebidas por Alberto e Bruno são, respectivamente, 80% e 7/8 da parte recebida por Carlos. Se Carlos desse R$25,00 a Bruno, ambos ficariam com o mesmo valor. Calcule o valor total inicial dividido entre as três pessoas.', '16', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1954, 'Matemática','A', 'https://i.imgur.com/zR1aVbp.png', '||A:1,6 + 0,125π#@||B:1,6 + 0,25π#@||C:1,6 + π#@||D:3,2 + 0,25π#@||E:3,2 + 0,125π#@', '', 'O desenho a seguir corresponde ao tradicional jogo de Amarelinha, muito comum entre as crianças.', 'Em relação ao desenho apresentado, considere que a medida de cada retângulo numerado de 1 a 8 tenha 0,5 m de largura por 0,4 m de comprimento e que o “CÉU” seja representado por um semicírculo justaposto aos retângulos de números 7 e 8. Considere, ainda, que os retângulos não estejam sobrepostos ou possuam espaços entre eles. Sendo assim, qual é a área total limitada pela figura em mˆ2?', '17', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1955, 'Matemática','E', '', '||A:I, V e VI#@||B:II, IV e VI#@||C:III, V e VI#@||D:I e V#@||E:II e IV#@', '', '', 'Considere as sentenças:
I. (xu{00B3})u{2074} = xu{2077}
II. (xu{00B3})u{2074} = xu{00B9}u{00B2}
III. (xu{00B3})u{2074} = xu{2078}u{00B9}
IV. xu{00B3}xu{2074}
VI. Para a,b e c números reais, se ab = ac, então b = c São verdadeiras as sentenças:', '18', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1956, 'Matemática','E', '', '||A:43%#@||B:57,5%#@||C:61,5%#@||D:73%#@||E:77%#@', '', '', 'Leia o texto a seguir:

 “A cidade de São Paulo atingiu 23% da meta de vacinação contra sarampo entre os jovens de 15 a 29 anos. Segundo a Secretaria Municipal de Saúde, de 10 de junho até esta quintafeira (25), foram aplicadas 720 mil doses da vacina.”.  Na cidade de São Paulo, após 25 de julho, foram vacinados 50% dos jovens de 15 a 19 anos que ainda não haviam recebido a vacina. Qual é a porcentagem total de jovens vacinados até essa data?', '19', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1957, 'Matemática','E', '', '||A:16#@||B:18#@||C:20#@||D:22#@||E:24#@', '', '', 'Uma  loja  de  eletrodomésticos  possui  uma  matriz  e  onze  filiais.  Ela  comprou  200  televisores  idênticos para serem  distribuídos  igualmente  entre  as  12  lojas,  ficando  a  matriz  também  com  o  resto  da  divisão.  O  número  de televisores destinados à matriz equivale a:', '20', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1958, 'Matemática','C', 'https://i.imgur.com/WeQjX8l.png', '||A:2 + √3#@||B:1/(2 − √3)#@||C:2 − √3#@||D:√3 − 1#@||E:#@', '', '', 'Na  figura  a  seguir,  temos  três  circunferências  de  raio 1,  tangentes  entre  si  e  inscritas  no  retângulo ABCD. Sabendo que M é ponto do segmento AD e que F, G e E são pontos de tangência entre as circunferências e os lados do retângulo, calcule o valor da tangente do ângulo MEF.', '21', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1959, 'Matemática','E', '', '||A:−1/7#@||B:−2/7#@||C:−3/7#@||D:−4/7#@||E:−5/7#@', '', '', 'Calcule a soma das raízes reais da equação (-x-3)/-4 - (-x+1)/3 = 1/x.', '22', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1960, 'Matemática','D', '', '||A:E = 0#@||B:E = 1#@||C:E = 9#@||D:E = 16#@||E:E = 34#@', '', '', 'Calcule o valor numérico da expressão E =  12[(1/3)+(5/6)+(11/12)]−3u{00B3}.', '23', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1961, 'Matemática','D', 'https://i.imgur.com/0YS0CPk.png', '||A:1/16#@||B:1/8#@||C:1/4#@||D:1/2#@||E:1#@', '', 'Calcule o valor de X, sabendo que a = 2020 e b = 2018.', '', '24', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1962, 'Ciências Naturais','C', 'https://i.imgur.com/Y14iOXz.png', '||A:o Polo Sul magnético da agulha da bússola aponta para o Polo Norte geográfico terrestre, aproximadamente.#@||B:o Polo Sul magnético da agulha da bússola é atraído pelo Polo Sul magnético da Terra.#@||C:o Polo Sul magnético da agulha da bússola aponta para o Polo Sul geográfico terrestre, aproximadamente.#@||D:o Polo Norte magnético da agulha da bússola aponta para o Polo Sul geográfico terrestre, aproximadamente.#@||E:os Polos magnéticos da agulha são atraídos pelos Polos magnéticos terrestres de mesma denominação.#@', '', '', 'Podemos  dizer  que  a  Terra e  a agulha  de  uma  bússola  comportamse  como  barras  de  ímãs, que  possuem polos magnéticos Norte e Sul. Na figura a seguir, o Polo Norte magnético da agulha da bússola aponta de forma aproximada para o Polo Norte geográfico terrestre.  Desta forma, podemos concluir que:', '25', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1963, 'Ciências Naturais','B', 'https://i.imgur.com/aSzc0hA.png', '||A:5,9 x 10u{00B2}u{2075} m.#@||B:4,5 x 10u{00B2}u{00B2} m.#@||C:1,5 x 10u{00B9}u{2075} m.#@||D:9,0 x 10u{00B9}u{2075} m.#@||E:1,5 x 10u{00B9}u{2074} m.#@', '', '', 'No  dia  10  de  abril  de  2019,  foi  publicada  a  primeira imagem de um buraco negro. Essa imagem foi produzida por  uma rede de telescópios como resultado  do  projeto  Event Horizon  Telescope, realizado  pela  Fundação  Nacional  de  Ciências  (National Science Foundation). O buraco negro fotografado possui uma massa 6,5 bilhões de  vezes  maior  que  a  massa  do  Sol,  e  se  encontra  a  5 milhões de anos luz da Terra. Considere que:
• 1 anoluz é a distância percorrida pela luz em um ano;
• 1 ano é aproximadamente igual a 3,0 x 10u{2077} s; • a velocidade da luz é igual a 3,0 x 10u{2075} km/s. Sendo assim, a distância do buraco negro observado em relação à Terra é de:', '26', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1964, 'Ciências Naturais','C', 'https://i.imgur.com/nRsGbhM.png', '||A:Em uma variação de altitude do nível do mar até uma altura de 1 km, observase, no gráfico, uma alteração de pressão como a observada em uma variação da altitude de 7 km até 8 km, pois a densidade do ar é a mesma em qualquer altitude.#@||B:Em uma variação de altitude do nível do mar até uma altura de 1 km, observase, no gráfico, uma alteração de pressão menor que a observada em uma variação da altitude de 7 km até 8 km, pois a densidade do ar diminui com o aumento da altitude.#@||C:Em uma variação de altitude do nível do mar até uma altura de 1 km, observase, no gráfico, uma alteração de pressão maior que a observada em uma variação da altitude de 7 km até 8 km, pois a densidade do ar diminui com o aumento da altitude.#@||D:O organismo humano pode sofrer alterações no seu comportamento quando a pressão atmosférica a que está submetido é de aproximadamente 0,9 atm.#@||E:A curva apresentada no gráfico não é uma reta, pois a densidade do ar é constante, independentemente da#@', '', 'Sabe-se  que  a  pressão  atmosférica  diminui  com  a  altitude,  e  essa diminuição causa alterações no comportamento do organismo humano. Numa  altura  de  aproximadamente  2.500  m  acima  do  nível  do  mar,  o organismo humano pode apresentar aumento na frequência cardíaca, dor de cabeça, náuseas, dificuldade para respirar, além de outros sintomas. O  gráfico  ao  lado fornece  o  comportamento  da  pressão  atmosférica  em relação à altitude.  Observe o gráfico e assinale a alternativa correta.', '', '27', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1965, 'Ciências Naturais','A', '', '||A:Retículo endoplasmático rugoso#@||B:Lisossomos#@||C:Mitocôndrias#@||D:Cloroplastos#@||E:Centríolos#@', '', '', 'Diabetes  Mellitus é  uma  doença que  apresenta  como  principal  sintoma  o  aumento  dos níveis  de  glicose  no sangue, condição denominada hiperglicemia. Ocorre principalmente por erros na síntese ou secreção do hormônio insulina,  um  polipeptídio  produzido  e  secretado  por  células especializadas,  localizadas  no  pâncreas.  Caso  um pesquisador iniciante desejasse realizar em laboratório um estudo sobre a organela diretamente relacionada com os erros na síntese da insulina, qual delas deveria ser o foco de suas pesquisas?', '28', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1966, 'Ciências Naturais','A', 'https://i.imgur.com/V1Jx3F9.png', '||A:As vacinas possuem agentes virais mortos ou atenuados, ou ainda substâncias virais que têm por finalidade formar a memória imunológica, que é específica para cada agente viral.#@||B:As vacinas possuem anticorpos que  irão realizar  o combate  aos agentes virais. Como os  anticorpos são específicos para cada doença, tornase necessário o recebimento de diferentes tipos de vacina.#@||C:As vacinas possuem antígenos capazes de combater os agentes virais, eliminando, assim, a possibilidade de  evolução  da  doença.  Como  muitos  vírus  possuem  altas  taxas  de  mutação,  tornase  necessário  o recebimento de diferentes tipos de vacina.#@||D:As vacinas possuem anticorpos capazes de gerar no paciente uma memória imunológica específica ao vírus causador  de  cada  doença.  Devido  à  diversidade  de  doenças  causadas  por  agentes  virais,  tornase necessária a utilização de diferentes vacinas.#@||E:As  vacinas  são  produzidas  a  partir  da  administração  de  antígenos  em  cavalos.  Os  anticorpos  são,  em#@', '', 'Leia o texto a seguir.', 'O  aumento  nos  casos  da  doença  evidenciada  no  texto  reforça  a  necessidade  da  realização  das campanhas  de vacinação como medida de promoção da saúde individual e coletiva. O motivo pelo qual devemos receber diferentes vacinas ao longo de nossa vida é:', '29', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1967, 'Ciências Naturais','C', '', '||A:as  abelhas,  ao  reconhecerem  os  campos  elétricos  das  flores, conseguem  selecionar  as  espécies  que produzem mais néctar, agindo como efetivas polinizadoras e dispersoras de sementes.#@||B:as  abelhas,  ao  reconhecerem  o  campo  elétrico  produzido  pela  interação  das  flores  com  a  atmosfera, conseguem perceber, com exatidão, as condições climáticas, realizando a polinização na primavera e de forma sincronizada.#@||C:a capacidade  dos  agentes  polinizadores  citados  no  texto  de  identificarem  os  tipos  de  flores  aumenta  as chances de que o pólen coletado em uma espécie seja depositado no estigma de uma outra flor de mesma espécie.#@||D:a capacidade das angiospermas de produzirem campos elétricos que facilitem o reconhecimento de suas flores  pelas  abelhas  aumenta  seu  sucesso  na  polinização  e  na  dispersão  das  sementes  em  relação  às pteridófitas, plantas que se reproduzem por esporos.#@||E:as abelhas, ao reconhecerem os campos elétricos de flores de diferentes espécies, conseguem buscar com#@', '', 'Leia o texto a seguir:

Abelhas utilizam campos elétricos para identificar flores A relação entre abelha e flor é tão intensa que alguns ecólogos atrelam o surgimento e a proliferação das abelhas na Terra ao aparecimento das plantas com flores e frutos (angiospermas). Para se alimentar, as abelhas utilizam os sentidos de visão e olfato, por meio dos quais reconhecem os diferentes tipos de flores por sua cor e cheiro. No entanto, existe outra forma de comunicação entre flores e abelhas bastante sofisticada. Invisíveis para os seres humanos,  os  campos elétricos  florais  são  estímulos  percebidos  por  um  sentido  especial  das  abelhas  que  elas também usam para reconhecer e identificar as flores. Em 2013, um estudo conduzido por Daniel Robert, biólogo da Universidade  de  Bristol,  Inglaterra,  e  publicado  pela Science (vol.  340,  pp.  66-69),  anunciava  uma  importante descoberta:  as  flores  estão  cercadas  por  um  campo  elétrico  fraco,  que  surge  da  interação  com  a  atmosfera.  As abelhas são capazes de detectar esses campos elétricos e, por meio do seu formato geométrico, identificar o tipo de flor. Adaptado de: FLORIO, V. Abelhas utilizam campos elétricos para identificar flores. In: Cienc. Cult. vol.68 no.3 São Paulo July/Sept. 2016.', 'Considerando o  texto,  o  reconhecimento  das  estruturas  florais,  a  partir  dos  campos  elétricos,  gerou  vantagem evolutiva para as angiospermas, pois', '30', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1968, 'Ciências Naturais','E', '', '||A:Os movimentos respiratórios são controlados pelo bulbo, órgão presente no tronco encefálico humano. O bulbo aumenta a frequência dos movimentos respiratórios quando há queda do oxigênio sanguíneo.#@||B:Os  movimentos  respiratórios  são  controlados  na  ponte,  órgão  presente  no  cérebro  humano.  A  ponte aumenta a frequência dos movimentos respiratórios quando há queda do oxigênio no sangue.#@||C:Os  movimentos  respiratórios  são  controlados  pela  ponte,  órgão  presente  no  cérebro  humano.  A  ponte aumenta a frequência dos movimentos respiratórios quando há aumento do gás carbônico sanguíneo.#@||D:Os  movimentos  respiratórios  são  controlados  pela  ponte,  órgão  presente  na  medula  espinal.  A  ponte aumenta a frequência dos movimentos respiratórios quando há queda do gás oxigênio sanguíneo.#@||E:Os movimentos respiratórios são controlados pelo bulbo, órgão presente no tronco encefálico humano. O#@', '', '', 'O mergulho livre ou mergulho em apneia pode ser muito perigoso se não praticado com responsabilidade, pois, apesar  da  respiração  poder  ser  interrompida  de  forma  voluntária,  o  controle  dos  movimentos  respiratórios  são involuntários. Sobre o mecanismo de controle da respiração, assinale a alternativa correta:', '31', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1969, 'Ciências Naturais','C', '', '||A:A  Amazônia não  pode  ser  considerada  o  pulmão  do  mundo,  pois,  devido  à  alta  taxa  de  transpiração, é responsável pela formação dos rios aéreos.#@||B:As algas são consideradas o pulmão do mundo por serem capazes de liberar oxigênio para a atmosfera e fixar o gás carbônico, pois não realizam respiração aeróbica, apenas fotossíntese.#@||C:A Amazônia não pode ser considerada o pulmão do mundo por ser uma floresta em clímax, ou seja, que já atingiu o último estágio da sucessão ecológica.#@||D:As  algas  são  consideradas  o  pulmão  do  mundo, pois  apresentam  baixa  taxa  de  reprodução,  realizando, assim, taxas mais elevadas de fotossíntese do que de respiração.#@||E:As  algas  são  consideradas  o  pulmão  do  mundo, pois  apresentam  baixa  taxa  de  transpiração,  já  que,#@', '', '', 'Leia o texto a seguir:

 Personalidades  e  o  próprio  senso  comum  tendem  a  repetir  que  a  maior  floresta  tropical  do  mundo  sirva  como pulmões  ao  planeta.  Do  ponto  de  vista  científico,  porém,  a  analogia  é  equivocada.  Os  pulmões  humanos  são responsáveis por uma troca gasosa essencial: eles nos fornecem oxigênio e eliminam o gás carbônico produzido pelo próprio corpo durante a queima energética. De acordo com o biólogo e pesquisador da Universidade Federal de  Minas  Gerais, Adriano  Paglia,  são  as  algas  marinhas,  vegetais  fotossintetizantes,  que  fazem  boa  parte  da liberação de oxigênio na atmosfera mundial. (Adaptado de: https://www.hojeemdia.com.br/horizontes/nocentrodapol%C3%AAmicaaamaz%C3%B4nia-%C3%A9-oun%C3%A3o-%C3%A9-opulm%C3%A3odomundo-1.737402. Acesso em: 23/08/2019).  Considerando as informações contidas no texto e os seus conhecimentos, assinale a alternativa correta:', '32', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1970, 'Ciências Naturais','B', 'https://i.imgur.com/AnzVIVS.png', '||A:A  explicação  apresentada  está  de  acordo  com  a teoria  darwinista,  pois  justifica  o  surgimento  da característica pela seleção dos mais aptos.#@||B:A explicação apresentada está de acordo com a teoria lamarckista, pois justifica a ocorrência da adaptação por sua finalidade.#@||C:A  explicação  apresentada  está  de  acordo  com  a  teoria  darwinista,  pois  justifica  o  surgimento  da característica pela lei do uso e desuso.#@||D:A explicação apresentada está de acordo com a teoria darwinista, pois justifica a presença da característica como consequência da necessidade.#@||E:A explicação apresentada está de acordo com a teoria lamarckista, pois justifica a presença da adaptação#@', '', 'A  tirinha  a  seguir  representa  Charles  Darwin,  o  principal  pensador  da  teoria  evolucionista  mais  aceita atualmente.  (https://esquadraodoconhecimento.files.wordpress.com/2011/12/darwin-1.png. Acesso em 25/08/2019.)', 'Analise a explicação apresentada no segundo quadrinho e assinale a alternativa correta.', '33', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1971, 'Ciências Naturais','D', '', '||A:4,2 e 33,2.#@||B:11,2 e 316,7.#@||C:2,7 e 332.#@||D:4,2 e 316,7.#@||E:11,2 e 33,2.#@', '', '', 'A hematita,  minério do qual se extrai o ferro  metálico, tem,  essencialmente, na sua constituição, o óxido  de ferro III (Fe2O3). As reações que ocorrem nesse processo siderúrgico podem ser resumidas pela equação: Fe2O3(s)  +  3 CO(g)   →    2 Fe(s)  +  3 CO2(g) Ao  se  adicionar  5,0  toneladas  de  Fe2O3,  serão  necessárias  2,7 toneladas  de  monóxido  de  carbono,  sendo produzidas  3,5  toneladas  de  ferro  metálico  e  _________  toneladas  de  CO2.  E,  ao  se  utilizar  452,5  kg  de  Fe2O3, serão produzidos, aproximadamente, _________ quilogramas de ferro metálico. Assinale a alternativa cujos valores preenchem, respectivamente, as lacunas.', '34', 54);
INSERT INTO question(id, topic, answer, images, options, subtitle, initial_text, text, number, test_id) values (1972, 'Ciências Naturais','A', '', '||A:o CO2 faz ligação covalente e é um óxido ácido.#@||B:o Fe2O3 faz ligação iônica e é um peróxido.#@||C:o CO faz ligação iônica e é um óxido neutro.#@||D:o SiO2 faz ligação iônica e é um óxido básico.#@||E:o CO e CO#@', '', '', 'Tanto  a hematita (Fe2O3) quanto a areia (SiO2) são classificadas como óxidos. Além disso, podemos incluir nesse mesmo grupo de funções inorgânicas o CO e o CO2, que são substâncias presentes no processo de obtenção do ferro metálico. Contudo, eles possuem diferenças em relação à ligação química e reatividade. Dessa forma, podemos afirmar que:', '35', 54);